CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD count_goal INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD count_goal INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);

ALTER TABLE team
    DROP COLUMN goalcount;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);

ALTER TABLE team
    DROP COLUMN goalcount;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);

ALTER TABLE team
    DROP COLUMN goalcount;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    DROP COLUMN goalcount;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;