CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD count_goal INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD count_goal INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);



DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

ALTER TABLE team
    ADD goal_count INTEGER;

CREATE UNIQUE INDEX IX_pk_game_state ON game_state (state_id);

CREATE UNIQUE INDEX IX_pk_matches ON matches (match_id);

CREATE UNIQUE INDEX IX_pk_team ON team (team_id);


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;


DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_league START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE league
    DROP COLUMN league_id;

ALTER TABLE league
    ADD league_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE matches
    DROP COLUMN league_id;

ALTER TABLE matches
    ADD league_id BIGINT;

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE matches
    ALTER COLUMN league_id DROP NOT NULL;

ALTER TABLE team
    DROP COLUMN league_id;

ALTER TABLE team
    ADD league_id BIGINT;

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE team
    ALTER COLUMN league_id DROP NOT NULL;

ALTER TABLE league
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE league
    DROP COLUMN league_id;

ALTER TABLE league
    ADD league_id DECIMAL GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE matches
    DROP COLUMN league_id;

ALTER TABLE matches
    ADD league_id DECIMAL;

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE team
    DROP COLUMN league_id;

ALTER TABLE team
    ADD league_id DECIMAL;

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE league
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE league
    DROP COLUMN league_id;

ALTER TABLE league
    ADD league_id numeric(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE matches
    DROP COLUMN league_id;

ALTER TABLE matches
    ADD league_id numeric(19, 0);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE team
    DROP COLUMN league_id;

ALTER TABLE team
    ADD league_id numeric(19, 0);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE league
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;
CREATE SEQUENCE IF NOT EXISTS sequence_match START WITH 1 INCREMENT BY 1;

DROP SEQUENCE stateseq CASCADE;

ALTER TABLE team
    ALTER COLUMN emblem TYPE VARCHAR(255) USING (emblem::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN features TYPE VARCHAR(255) USING (features::VARCHAR(255));

ALTER TABLE matches
    DROP COLUMN league_id;

ALTER TABLE matches
    ADD league_id INTEGER;

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE team
    DROP COLUMN league_id;

ALTER TABLE team
    ADD league_id INTEGER;

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_LEAGUE_ID FOREIGN KEY (league_id) REFERENCES league (league_id);

ALTER TABLE league
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE team
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE team
    ALTER COLUMN power DROP NOT NULL;